pipeline{
   agent any
   tools{
       maven '3.6.3'
   }
   stages{
      stage("source"){
          steps{
             git branch: 'main' ,url:''
        }
      }
      stage ('build'){
        steps
      }
   }
}